// Generated by CoffeeScript 1.7.1
(function() {
  var confirmDelete;

  $(document).on('click', '.transaction-list li a', function(e) {
    var transaction;
    transaction = $(this).parents('li');
    return confirmDelete(transaction);
  });

  confirmDelete = function(transaction) {
    var $confirm;
    transaction.addClass('ui-btn-down-d');
    $confirm = $('#confirm');
    $confirm.find('.location').remove();
    transaction.find('.location').clone().insertAfter('#question');
    $confirm.popup('open');
    $confirm.find('#yes').on('click', function() {
      $.ajax('/transaction/delete', {
        type: 'POST',
        data: {
          id: transaction.find('input').val()
        }
      });
      transaction.removeClass('ui-btn-down-d');
      transaction.addClass('right');
      transaction.on('webkitTransitionEnd transitionend otransitionend', function() {
        return transaction.remove();
      });
      transaction.prev('li').addClass('border');
    });
    $confirm.find('#cancel').on('click', function() {
      transaction.removeClass('ui-btn-down-d');
      return $confirm.find('#yes').off();
    });
  };

  return;

}).call(this);

//# sourceMappingURL=Transactions.map
